### ISSUE TITLE
Add various changes to the landing page, and other login fields

### ISSUE THREAD

**Issue by kevintodd36** [xlab-classes/cse442-spring2022-team-smooth-stock#103]
**Acceptance Tests:**

_Test 1_ 
1) Click on forgot password link, enter Smoothstocksapp@gmail.com as the email and press submit
2) Confirm a new text box has appeared at the top that reads: "Reset password email sent! If you didn't receive an email enter your email again and press send."

_Test 2_
1) Log into an account (Username: Smoothstocksapp, Password: P@ssword123)
2) Confirm that when typing in the password it is blocked out.
3) Repeat the above steps but in the create account link tab.

_Test 3_
1) Log into an account (Username: Smoothstocksapp, Password: P@ssword123)
2) Log in and confirm there is no longer a log out button on the landing page

**Comment by amoghjos** [comment]
The task does not follow styleguide
