### ISSUE TITLE
Create news box on discover page for scraped news articles pertaining to selected stocks

### ISSUE THREAD

**Issue by jakeheidman** [xlab-classes/cse442-spring2022-team-smooth-stock#105]
**Task Tests**

*Test 1*

1. Navigate to the smooth stocks website: http://www-student.cse.buffalo.edu:6777/
2. Login with the username: mdlaszlo and password: Fakepass1
3. Navigate to the discover stocks page, and type in the following stocks: aapl, twtr, msft and make sure that you can see the news articles that show up.

**Comment by amoghjos** [comment]
Task does not follow styleguide
