### ISSUE TITLE
As a stock trader, I want to create an account so that I can save time by storing information about my stocks preferences

### ISSUE THREAD

**Issue by kevintodd36** [xlab-classes/cse442-spring2022-team-smooth-stock#17]
**Acceptance test** 

*Test 1*
1) Download landing page code from https://github.com/xlab-classes/cse442-spring2022-team-smooth-stock
2) Upload project on PyCharm IDE, click run
2) Go to website localhost:8000/smoothstocks
3) Click create account
4) Input "user_one" as username and "P@ssword_321" as password
5) Click create account
6) Return to login page
7) Put in "user_one" into username field, and "P@ssword_321" into password field
8) Click login

**Comment by amoghjos** [comment]
Hey @kevintodd36, the user story is hooked with tasks in incorrect flow. It should only say "Blocked by" instead of "Blocking"
