### ISSUE TITLE
As a stock trader, I want to be notify when the stock prices changes/if there's any news

### ISSUE THREAD

**Issue by DavidTan1** [xlab-classes/cse442-spring2022-team-smooth-stock#19]
**Acceptance Tests:**

_Test 1_ 
1) Register for an account
2) Login after registering
3) Choose a fake stock from the list to follow
4) Make fake stock go down a certain percentage
5) User is notified through email or discord that fake stock price when down/up

**Comment by amoghjos** [comment]
Hi @DavidTan1, I'm not sure why this issue is in testing pipeline...
