### ISSUE TITLE
Link discord and email to notification page

### ISSUE THREAD

**Issue by DavidTan1** [xlab-classes/cse442-spring2022-team-smooth-stock#37]
**Task Tests**

_Test 1_

1) Download code from Github.
2) Open notify.html in html folder.
3) Enter email in textbox, and click 'change email'.
4) Check email to verify linkage.

_Test 2_

1) Download code from Github.
2) Start the Discord bot.
2) Open notify.html in html folder.
3) Click 'change discord'.
4) Sign into discord account
5) Check discord to confirm linkage.
6) Verify bot said hello to you.

**Comment by amoghjos** [comment]
Hi @DavidTan1, I loved your demo but can you add more detailed steps in your task tests?
