### ISSUE TITLE
Enable Follow Button to send a real user's data to the database instead of a hardcoded test case in the /follow route

### ISSUE THREAD

**Issue by miclaszlo** [xlab-classes/cse442-spring2022-team-smooth-stock#76]
_Test 1_

1.Pull dev branch of group repo onto local machine. (https://github.com/xlab-classes/cse442-spring2022-team-smooth-stock/tree/dev)
2. Open in code in Visual Studio Code
3. In the terminal use the command 'ssh <your_ubid>@cheshire.cse.buffalo.edu'
4. Enter UBID password to login to chesire
5. In the terminal use the command 'cd /web/CSE442-542/2022-Spring/cse-442q' to enter Smooth Stock team directory
6. Run command 'mysql -h oceanus -u <UBID> -p'
7. Enter person number 
8. Run command 'USE cse442_2022_spring_team_q_db ;'
9. Run command 'SHOW Tables;' to verify that saved_stocks Table exists
10. In Visual studio code cd into the src folder
11. In Visual studio code run 'flask app'
12. Try to Navigate to 127.0.0.1:5000/discover and verify User needs to be logged in
13. Log in using username of 'fakeuser' and password of 'aBc12345'
14. Navigate to 127.0.0.1:5000/discover again and verify that discover page is shown
15. Run command in terminal 'SELECT * FROM saved_stocks' to verify that fakeuser is currently following AAPL
16. Search 'AAPL' on discover page
17. Verify that 'AAPL' stock information appears and the button on the page says 'Unfollow Stock'
18. Press 'Unfollow Stock' Button
19. Run command in terminal 'SELECT * FROM saved_stocks' to verify that fakeuser is now not following AAPL
20. Search 'AAPL' again on discover page
21. Verify that 'AAPL' stock information appears and the button on the page says 'Follow Stock'

**Comment by amoghjos** [comment]
Same issue #81
