### ISSUE TITLE
Send out notification to users from follow_stock database when price change

### ISSUE THREAD

**Issue by DavidTan1** [xlab-classes/cse442-spring2022-team-smooth-stock#80]
**Task Tests**

_Test 1_
1. cd into src folder
2. Type in flask run in terminal
3. Go to notification page (Assume you are already login)
4. Follow the stock APPL.
5. Check the stocks you're already following stocks.
6. Update price of APPL.
7. Check email notification when price change.

**Comment by amoghjos** [comment]
Hi @DavidTan1, this is not really actual META stock price tho, so moving this task back to testing.

**Comment by amoghjos** [comment]
Hi @DavidTan1, you can't close an issue by yourself also, you should first move it to completed and then close it...
