### ISSUE TITLE
Show user contact information in notification page and allow user to change email

### ISSUE THREAD

**Issue by DavidTan1** [xlab-classes/cse442-spring2022-team-smooth-stock#97]
_Test 1_

1. Navigate to the website: http://www-student.cse.buffalo.edu:6777/
2. Login into the account using the following credentials (username: test_acc_23, password: 1qAzxsw23)
3. Click on notification tab after logging in. 
4. Confirm correct email is currently display in the textbox.
5. Enter a new email into the textbox.
6. Click the change email button.
7.  Confirm new email is correctly display in the textbox.

**Comment by amoghjos** [comment]
Task does not follow styleguide
