### ISSUE TITLE
Organize and debug python code and html such that all the cosmetic issues such as the navigation bar are fixed. 

### ISSUE THREAD

**Issue by jiaweirgb** [xlab-classes/cse442-spring2022-team-smooth-stock#98]
**Task Tests**

_Test 1_
1) Create an account on the testing link http://www-student.cse.buffalo.edu:6078/, or the latest test link posted in discord
2) Follow some stocks.
3) Verify the names and prices display as expected. 
4) Go to github's develop branch https://github.com/xlab-classes/cse442-spring2022-team-smooth-stock/tree/DEVELOP/src
5) Verify that the deprecated functions have been removed from app.py (obtain_stocks method) and replaced with better working ones(obtain method). 

_Test 2_
1) Create an account on the testing link http://www-student.cse.buffalo.edu:6078/, or the latest test link posted in discord
2) Follow some stocks.
3) Go  to http://www-student.cse.buffalo.edu:6078/442
4) Verify the 442 navigation bar is as the PM has described. (Back, discover, news, prices, notifications, prev)
5) Verify the support navigation bar is as the PM has described. (back, discover, news, prices, notifications, prev)
6) Verify the energy1 navigation bar is as the PM has described.(back, discover, news, prices, notifications, prev)
7) Verify the tech1 navigation bar is as the PM has described.(back, discover, news, prices, notifications, prev)
8) Verify the telecom1 navigation bar is as the PM has described. (back, discover, news, prices, notifications, prev)

**Comment by amoghjos** [comment]
Task does not follow styleguide
